before_script:
  - uname -a
  - cat /etc/issue

stages:
  - build
  - test
  - deploy

variables:
  IMAGE: rego.corp.nucleisys.com/software/sdkbuild
  IMAGE_TAG: "2025.02"

workflow:
  rules:
    # ignore commit with draft/wip/stash
    - if: $CI_COMMIT_MESSAGE =~ /draft|wip|stash/i
      when: never
    # open merge quest and request target branch is nuclei*
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /nuclei/ && $CI_PIPELINE_SOURCE == "merge_request_event"
    # no open merge request and branch pipeline
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH =~ /nuclei/ || $CI_COMMIT_TAG

default:
  interruptible: true

prepare_tools:
  stage: build
  interruptible: true
  #  when: manual
  timeout: 3h
  script:
    # prepare for docker ssh environment
    ## https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor
    - apt update
    - command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # important: need to avoid git ssh asking yes/no when clone
    # https://serverfault.com/questions/469052/ssh-failing-from-script-working-on-command-line-git
    - ssh-keyscan gito > ~/.ssh/known_hosts
    - ssh-keyscan gito.corp.nucleisys.com >> ~/.ssh/known_hosts
    - ssh -T git@gito
    - ssh -T git@gito.corp.nucleisys.com
    - python3 -m pip install --upgrade pip
    - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - mkdir -p $CI_PROJECT_DIR/prebuilt/
    - cd $CI_PROJECT_DIR/prebuilt/
    # test sdk
    - mkdir -p $CI_PROJECT_DIR/prebuilt/
    - cd $CI_PROJECT_DIR/prebuilt/
    # use nuclei sdk develop branch for testing
    - git clone -b develop --depth 1 git@gito.corp.nucleisys.com:software/library/nuclei-sdk.git
    - cd nuclei-sdk
    - git describe --tags --always --abbrev=10 > build.txt
    # rm unused .git
    - rm -rf .git
    # nmsis
    - cd $CI_PROJECT_DIR/prebuilt/
    # use NMSIS master branch for testing
    - git clone --depth 3 -b master git@gito.corp.nucleisys.com:software/library/NMSIS.git
    - cd NMSIS
    - git describe --tags --always --abbrev=10 > build.txt
    # rm unused .git
    - rm -rf .git
    - du -sh $CI_PROJECT_DIR/prebuilt
  tags:
    - env::docker
    - net::outside
  image: $IMAGE:$IMAGE_TAG
  allow_failure: true
  artifacts:
    when: always
    paths:
    - $CI_PROJECT_DIR/prebuilt

.build_job_template: &build_job_template_default
  stage: build
  timeout: 1h
  interruptible: true
  # https://docs.gitlab.com/ee/ci/yaml/index.html#retrywhen
  retry:
    max: 2
    when:
      # ERROR: Job failed (system failure): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (docker.go:534:120s)
      - runner_system_failure
  before_script:
    # check toolchain repo status
    - uname -a
    - cd $CI_PROJECT_DIR
    - |
        echo "Try to cleanup this repo first"
        # clean up this repo
        git clean -ffdx || true
        git submodule foreach --recursive git clean -xfdf || true
        echo "INFO: Show current repo status"
        git status --ignored=matching || true
        git submodule status --recursive || true
        # show also untracked files
        git submodule foreach git status --ignored=matching || true
    # workaround for clone source code using mirror in gito
    - sed -i 's|https://gitlab.com/qemu-project|https://gito.corp.nucleisys.com/software/qemu|g' .gitmodules
    - |
        echo "INFO: Try to full clone source code now!"
        echo "Just update submodule without recursive"
        # sync submodule url first due to submodule url modified
        git submodule init
        git submodule sync
        git submodule foreach git remote -v
        git submodule update --force --init
        git submodule foreach --recursive git reset --hard || true
        #echo "Try to update submodule recursively"
        #for i in $(seq 1 2); do
        #    git submodule update --force --recursive --init && break || {
        #        echo "Attemp $i failed, retrying..."
        #        git submodule foreach --recursive git reset --hard || true
        #        sleep 1
        #    }
        #done
        # reset changes to default HEAD
        git reset --hard || true
        git submodule sync
        git status
        git submodule status --recursive || true
    - echo "Nuclei Qemu Source code is ready, git commit hash is $(git describe)!"

build_linux_qemu:
  <<: *build_job_template_default
  tags:
    - os::linux
    - env::docker
  image: rego.corp.nucleisys.com/software/build-linux-qemu:latest
  script:
    # build
    - cd $CI_PROJECT_DIR
    - mkdir $CI_PROJECT_DIR/build -p
    - mkdir $CI_PROJECT_DIR/linux_qemu -p
    - cd build
    - ../configure --prefix=$CI_PROJECT_DIR/linux_qemu --disable-pa --disable-linux-aio --disable-rbd --disable-vnc --disable-sdl --disable-sdl-image --target-list=riscv32-softmmu,riscv64-softmmu,riscv64-linux-user,riscv32-linux-user
    - make -j8
    - make install
    - echo "Linux qemu is successfully built, but not stripped"
  artifacts:
    name: "qemu_linux_${CI_COMMIT_SHORT_SHA}"
    paths:
      - $CI_PROJECT_DIR/linux_qemu

build_windows_qemu:
  <<: *build_job_template_default
  tags:
    - os::linux
    - env::docker
  image:
    name: rego.corp.nucleisys.com/software/build-windows-qemu:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    # build
    - mkdir $CI_PROJECT_DIR/build -p
    - mkdir $CI_PROJECT_DIR/windows_qemu/bin -p
    - cd build
    - ../configure --cross-prefix=x86_64-w64-mingw32- --target-list=riscv32-softmmu,riscv64-softmmu --prefix=$CI_PROJECT_DIR/windows_qemu/bin
    - make -j8
    - make install
    # copy necessary dlls required by qemu
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/* $CI_PROJECT_DIR/windows_qemu/bin
    - echo "Windows qemu is successfully built, but not stripped"
  artifacts:
    name: "qemu_windows_${CI_COMMIT_SHORT_SHA}"
    paths:
      - $CI_PROJECT_DIR/windows_qemu

test_sdk:
  stage: test
  timeout: 4h
  #when: manual
  interruptible: true
  script:
    # find qemu and gcc
    - cd $CI_PROJECT_DIR
    - export QEMU_PATH_LINUX=$(readlink -f linux_qemu/bin)
    - export PATH=$QEMU_PATH_LINUX:$PATH
    #- export PATH=$CI_PROJECT_DIR/prebuilt/gcc/gcc/bin:$PATH
    - qemu-system-riscv32 --version
    - riscv64-unknown-elf-gcc -v
    ################################################
    - cd $CI_PROJECT_DIR/prebuilt/nuclei-sdk
    - pip3 install -r tools/scripts/requirements.txt
    - export NUCLEI_SDK_ROOT=$(readlink -f $CI_PROJECT_DIR/prebuilt/nuclei-sdk)
    - |
      HWCFG=${CI_PROJECT_DIR}/.gitlab/nsdk_ci.json
      if [ ! -f ${HWCFG} ] ; then
        HWCFG=${NUCLEI_SDK_ROOT}/tools/scripts/nsdk_cli/configs/nuclei_fpga_eval_ci_bpv.json
      fi
      echo "Using HWCFG=${HWCFG}"
    - python3 tools/scripts/nsdk_cli/nsdk_bench.py --appcfg tools/scripts/nsdk_cli/configs/application.json --hwcfg ${HWCFG} --parallel=-j --logdir logs/nuclei_fpga_eval_qemu_ci --run --run_target "qemu"
  tags:
    - os::linux
    - env::docker
  image: $IMAGE:$IMAGE_TAG
  allow_failure: true
  artifacts:
    name: "qemu_test_sdk_job${CI_JOB_ID}_${CI_COMMIT_SHA::8}"
    when: always
    paths:
      - $CI_PROJECT_DIR/prebuilt/nuclei-sdk/logs/

test_nmsis:
  stage: test
  timeout: 4h
  when: manual
  interruptible: true
  script:
    # find qemu and gcc
    - cd $CI_PROJECT_DIR
    - export QEMU_PATH_LINUX=$(readlink -f linux_qemu/bin)
    - export PATH=$QEMU_PATH_LINUX:$PATH
    #- export PATH=$CI_PROJECT_DIR/prebuilt/gcc/gcc/bin:$PATH
    - qemu-system-riscv32 --version
    - riscv64-unknown-elf-gcc -v
    ############################################################
    - cd $CI_PROJECT_DIR/prebuilt/NMSIS/
    - export NUCLEI_SDK_ROOT=$(readlink -f $CI_PROJECT_DIR/prebuilt/nuclei-sdk)
    - export NMSIS_LOGS=$(pwd)/NMSIS/Logs
    - mkdir $NMSIS_LOGS
    # change ilm/dlm size from 64K to 1M for evalsoc
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/gcc_evalsoc_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - cd $CI_PROJECT_DIR/prebuilt/NMSIS/NMSIS
    - pip3 install -r $NUCLEI_SDK_ROOT/tools/scripts/requirements.txt
    - |
      APPCFG=${CI_PROJECT_DIR}/.gitlab/nmsis_dsp_ci.json
      if [ ! -f ${APPCFG} ] ; then
        APPCFG=Scripts/Runner/nmsis_dsp_mini.json
      fi
      echo "Using APPCFG=${APPCFG} for NMSIS DSP"
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg ${APPCFG} --logdir $NMSIS_LOGS/nmsis_dsp --parallel=-j --run_target qemu --run
    - |
      APPCFG=${CI_PROJECT_DIR}/.gitlab/nmsis_nn_ci.json
      if [ ! -f ${APPCFG} ] ; then
        APPCFG=Scripts/Runner/nmsis_nn_mini.json
      fi
      echo "Using APPCFG=${APPCFG} for NMSIS NN"
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg ${APPCFG}  --logdir $NMSIS_LOGS/nmsis_nn  --parallel=-j --run_target qemu --run
  tags:
    - os::linux
    - env::docker
  image: $IMAGE:$IMAGE_TAG
  allow_failure: true
  artifacts:
    when: always
    name: "qemu_test_nmsis_job${CI_JOB_ID}_${CI_COMMIT_SHA::8}"
    paths:
      - $CI_PROJECT_DIR/prebuilt/NMSIS/NMSIS/Logs

make_qemu_zip:
  stage: deploy
  resource_group: deploy
  interruptible: true
  dependencies:
    - build_linux_qemu
    - build_windows_qemu
  script:
    - if [ ${CI_COMMIT_TAG} ] ; then export qemuver=${CI_COMMIT_TAG/nuclei-/} ; else export qemuver=$(date +%Y.%m.%d) ; fi
    - export QEMU_VER=${qemuver}
    - echo "This job deploy qemu release ${QEMU_VER} from the $CI_COMMIT_BRANCH branch."
    - ls -al
    - mkdir -p $CI_PROJECT_DIR/prebuilt
    - pushd $CI_PROJECT_DIR/prebuilt
    - popd
    - echo "Please refer to the online documentation:https://doc.nucleisys.com/nuclei_tools/qemu/index.html" >> windows_qemu/readme.md
    - echo "Please refer to the online documentation:https://doc.nucleisys.com/nuclei_tools/qemu/index.html" >> linux_qemu/readme.md
    - mkdir -p windows_qemu_workdir
    - mkdir -p linux_qemu_workdir
    # windows qemu
    - cd $CI_PROJECT_DIR
    - mv windows_qemu windows_qemu_workdir/qemu
    - cd $CI_PROJECT_DIR/windows_qemu_workdir/qemu
    - |
        szbefore=$(du -sh . | cut -f1)
        echo "Try to strip windows qemu, size is $szbefore"
        for fnd in `find . -type f \( -executable -o -name "*.so*" \) 2>/dev/null`; do
            echo "Try to strip $fnd"
            strip --strip-unneeded $fnd 2> /dev/null || true
        done
        szafter=$(du -sh . | cut -f1)
        echo "Windows qemu size stripped from $szbefore to $szafter"
    - cd ../
    - zip -qr nuclei-qemu-${QEMU_VER}-win32-x64.zip qemu
    - cp nuclei-qemu-${QEMU_VER}-win32-x64.zip $CI_PROJECT_DIR/
    # linux qemu
    - cd $CI_PROJECT_DIR
    - mv linux_qemu linux_qemu_workdir/qemu
    - cd $CI_PROJECT_DIR/linux_qemu_workdir/qemu
    - |
        szbefore=$(du -sh . | cut -f1)
        echo "Try to strip linux qemu, size is $szbefore"
        for fnd in `find . -type f \( -executable -o -name "*.so*" \) 2>/dev/null`; do
            echo "Try to strip $fnd"
            strip --strip-unneeded $fnd 2> /dev/null || true
        done
        szafter=$(du -sh . | cut -f1)
        echo "Linux qemu size stripped from $szbefore to $szafter"
    - echo "Check Nuclei QEMU ${QEMU_VER} version"
    - ./bin/qemu-system-riscv32 --version
    - ldd ./bin/qemu-system-riscv32
    - cd ../
    - tar -zcf nuclei-qemu-${QEMU_VER}-linux-x64.tar.gz qemu
    - cp nuclei-qemu-${QEMU_VER}-linux-x64.tar.gz $CI_PROJECT_DIR/
    - cd ${CI_PROJECT_DIR}
    # version
    - echo ${QEMU_VER} > $CI_PROJECT_DIR/VERSION
    # copy nuclei qemu to deploy folder
    - |
        pushd $CI_PROJECT_DIR
        rm -rf deploy
        mkdir -p deploy
        echo "Move built nuclei-qemu tools into deploy/ folder"
        mv nuclei-qemu-${QEMU_VER}-linux-x64.tar.gz deploy/
        mv nuclei-qemu-${QEMU_VER}-win32-x64.zip deploy/
        pushd deploy
        for sf in nuclei-qemu-${QEMU_VER}-linux-x64.tar.gz nuclei-qemu-${QEMU_VER}-win32-x64.zip ; do
            shasum -a 256 $sf > $sf.sha
        done
        echo "Show SHA256 Sum of Nuclei Qemu Tools"
        cat *.sha
        popd
        popd
    - echo "Nuclei qemu stripped zip successfully made, please download it from job artifacts"
  tags:
    - env::shell
    - user::xl_ci
  artifacts:
    name: "qemu_deploy_${CI_COMMIT_TIMESTAMP::10}_${CI_COMMIT_SHORT_SHA}"
    when: always
    paths:
      - $CI_PROJECT_DIR/deploy
      - VERSION

deploy-qemu:
  stage: deploy
  resource_group: deploy
  allow_failure: true
  interruptible: true
  rules:
    # manual trigger this deploy job on not merge request pipeline
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
  needs:
    - job: make_qemu_zip
      artifacts: true
  script:
    - export QEMU_VER=$(cat VERSION)
    - shareloc="/home/share/devtools/qemu"
    - echo "This job deploy qemu release ${QEMU_VER} to share environment $shareloc in 30s, you can cancel this job, if you click it wrongly"
    - sleep 30
    # zip qemu deploy package
    - |
        qemu_deploy_zip=qemu_deploy_${QEMU_VER}.zip
        echo "Zip qemu built packages into ${qemu_deploy_zip}"
        zip -r ${qemu_deploy_zip} VERSION Documents deploy
        # deploy qemu into share environment
        rm -rf qemu
        tar -xzf deploy/nuclei-qemu-${QEMU_VER}-linux-x64.tar.gz
        echo "Move qemu ${QEMU_VER} to ${shareloc}/linux64/"
        rm -rf ${shareloc}/linux64/${QEMU_VER}
        mv qemu ${shareloc}/linux64/${QEMU_VER}
        echo "Check Nuclei QEMU ${QEMU_VER} Version"
        $shareloc/linux64/${QEMU_VER}/bin/qemu-system-riscv32 --version
        echo "Copy ${qemu_deploy_zip} to ${shareloc}/deploy/"
        mv ${qemu_deploy_zip} ${shareloc}/deploy/
        ls -lht ${shareloc}/deploy/
    - echo "Qemu successfully deployed to share environment $shareloc/linux64/${QEMU_VER}"
  tags:
    - env::shell
    - user::xl_ci
  artifacts:
    name: "qemu_deploy_${CI_COMMIT_TIMESTAMP::10}_${CI_COMMIT_SHORT_SHA}"
    when: always
    paths:
      - $CI_PROJECT_DIR/deploy
      - VERSION

link-qemu:
  stage: deploy
  resource_group: deploy
  allow_failure: true
  interruptible: true
  needs:
    - job: deploy-qemu
      artifacts: true
  rules:
    # manual trigger this deploy job on not merge request pipeline
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      when: manual
  script:
    - export QEMU_VER=$(cat VERSION)
    - shareloc="/home/share/devtools/qemu/linux64"
    - echo "This job link qemu release ${QEMU_VER} to latest in share environment $shareloc in 30s, you can cancel this job, if you click it wrongly"
    - sleep 30
    - |
      echo "Show last latest qemu linked to, and wait to confirm latest will link to ${QEMU_VER} now"
      ls -l $shareloc/latest
      echo "Check last latest Qemu Version"
      $shareloc/latest/bin/qemu-system-riscv32 --version
      sleep 30
      rm -f $shareloc/latest
      pushd $shareloc
      echo "Do symbolic link ${QEMU_VER} -> latest"
      ln -s ${QEMU_VER} latest
      popd
      echo "Check Latest Qemu Version"
      $shareloc/latest/bin/qemu-system-riscv32 --version
    - echo "Nuclei Qemu successfully link ${QEMU_VER} to latest in $shareloc"
  tags:
    - env::shell
    - user::xl_ci
