before_script:
  - uname -a
  - cat /etc/issue

prepare_tools:
  stage: build
  timeout: 2h 30m
  script:
    - echo "hello world"
    - mkdir -p $CI_PROJECT_DIR/tools/
    - cd $CI_PROJECT_DIR/tools/
    # docs
    - git clone git@gito.corp.nucleisys.com:software/riscv-gnu-toolchain/qemu.wiki.git
    # gcc
    - mkdir -p $CI_PROJECT_DIR/tools/gcc
    # /home/xl_ci/toolchain//nuclei_gnu/linux64/newlibc/2021.1215.eng1/gcc
    #- cp /home/xl_ci/toolchain/nuclei_gnu/linux64/newlibc/2021.11-eng1/gcc/ gcc/ -r
    # 2021.07-eng1
    - cp /home/xl_ci/toolchain/nuclei_gnu/linux64/newlibc/2022.04/gcc/ gcc/ -r
    #- cp /home/xl_ci/toolchain/nuclei_gnu/linux64/newlibc/2021.09-rvp-eng2-linux/gcc/ gcc/ -r
    - export PATH=$CI_PROJECT_DIR/tools/gcc/gcc/bin:$PATH
    # test sdk
    - mkdir -p $CI_PROJECT_DIR/tools/sdk
    - cd $CI_PROJECT_DIR/tools/sdk
    - git clone git@gito.corp.nucleisys.com:software/library/nuclei-sdk.git
    - cd nuclei-sdk
    # nmsis
    - cd  $CI_PROJECT_DIR/tools/
    - git clone git@gito.corp.nucleisys.com:software/library/NMSIS.git
    - cd $CI_PROJECT_DIR/tools/NMSIS/NMSIS
    - git clone git@gito.corp.nucleisys.com:software/library/nuclei-sdk.git
    - cd nuclei-sdk
    - git checkout dev_xlspike_next
    - sed -i "s/64K/1M/g" SoC/demosoc/Board/nuclei_fpga_eval/Source/GCC/gcc_demosoc_ilm.ld
    - cd $CI_PROJECT_DIR/tools/NMSIS/NMSIS/
    # build dsp lib
    - make gen
    #- make strip_dsp_lib
    # build nn lib
    - make gen_unalign
    #- make strip_nn_lib
    - cd $CI_PROJECT_DIR/tools/NMSIS/NMSIS/nuclei-sdk
    - pip3 install -r tools/scripts/requirements.txt
    - cd $CI_PROJECT_DIR/tools/NMSIS/
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - make gen
    - make gen_nnref_lib
    #git submodule
    - cd $CI_PROJECT_DIR/tools
    - git clone git@gito.corp.nucleisys.com:software/qemu/internal-submudule.git
    - cd $CI_PROJECT_DIR
    - cp $CI_PROJECT_DIR/tools/qemu_submodule .gitmodules
  tags:
    - env::native
    - host::xls01
  allow_failure: true
  artifacts:
    when: always
    paths:
    - $CI_PROJECT_DIR/tools/


build_linux_qemu:
  stage: build
  tags:
    - os::linux
    - env::docker
  image: rego.corp.nucleisys.com/software/build-linux-qemu:v1
  script:
    # - apt-get -y update --fix-missing 
    # - apt-get install -y --fix-missing git build-essential pkg-config zlib1g-dev libglib2.0-0 libglib2.0-dev libpixman-1-dev autoconf automake libtool flex bison make
    # # gcc 7.5
    # - apt-get install -y software-properties-common
    # - apt-get install wget openssl libssl-dev -y
    # - wget http://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
    # - tar -xvzf Python-3.6.4.tgz
    # - cd Python-3.6.4
    # - ./configure --with-ssl
    # - make -j8 && make install
    # - which python3
    # - rm /usr/bin/python && ln -s /usr/local/bin/python3 /usr/bin/python
    # - ln -s -f /usr/local/python3/bin/pip3  /usr/bin/pip3  && ln -s -f /usr/local/bin/pip3 /usr/bin/pip
    # - pip3 install ninja
    # - pip3 install meson==0.57.2
    # git submodule
    - cd $CI_PROJECT_DIR
    - git submodule sync
    - git submodule update --init
    - git submodule update --remote
    - sync
    # glib
    #build
    - cd $CI_PROJECT_DIR
    - mkdir $CI_PROJECT_DIR/build -p
    - mkdir $CI_PROJECT_DIR/linux_qemu -p
    - cd build
    - ../configure --disable-werror --prefix=$CI_PROJECT_DIR/linux_qemu --disable-vnc --disable-sdl --disable-sdl-image --target-list=riscv32-softmmu,riscv64-softmmu && make -j8 && make install
  artifacts:
    paths:
    - $CI_PROJECT_DIR/linux_qemu
    - $CI_PROJECT_DIR/tools

build_windows_qemu:
  stage: build
  tags:
    - os::linux
    - env::docker
  image: 
    name: rego.corp.nucleisys.com/software/build-windows-qemu:v1
    entrypoint: ["/bin/sh", "-c"]
  script:
    # install software
    # - dnf install updates
    # - dnf install -y git mingw64-pixman mingw64-gmp mingw64-SDL2 mingw64-pkg-config mingw64-bzip2 bzip2 make diffutils pkg-config autoconf automake libtool flex bison
    # - dnf install -y http://ftp.pbone.net/mirror/archive.fedoraproject.org/fedora-secondary/releases/28/Everything/ppc64/os/Packages/m/mingw64-glib2-2.54.1-1.fc28.noarch.rpm
    # - dnf install -y ninja-build
    # - dnf install -y gcc
    # - dnf install -y https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/aarch64/os/Packages/m/meson-0.56.2-2.fc34.noarch.rpm
    - git submodule sync
    - git submodule update --init
    - git submodule update --remote
    #- git submodule update --remote
    - sync
    # build
    - mkdir $CI_PROJECT_DIR/build -p
    - mkdir $CI_PROJECT_DIR/windows_qemu/bin -p
    - cd build
    - ../configure --disable-werror --cross-prefix=x86_64-w64-mingw32- --target-list=riscv32-softmmu,riscv64-softmmu --prefix=$CI_PROJECT_DIR/windows_qemu/bin && make -j8 && make install 
    - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/* $CI_PROJECT_DIR/windows_qemu/bin
  artifacts:
    paths:
    - $CI_PROJECT_DIR/windows_qemu

test_sdk:
  stage: test
  timeout: 2h 30m
  script:
    - apt-get -y update --fix-missing 
    - apt-get install -y --fix-missing git build-essential pkg-config zlib1g-dev libglib2.0-0 libglib2.0-dev libpixman-1-dev autoconf automake libtool flex bison make
    #- apt-get install -y python3-pip
    - apt-get install -y software-properties-common
    - apt-get install wget openssl libssl-dev -y
    - wget http://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
    - tar -xvzf Python-3.6.4.tgz
    - cd Python-3.6.4
    - ./configure --with-ssl
    - make -j8 && make install
    - which python3
    - rm /usr/bin/python && ln -s /usr/local/bin/python3 /usr/bin/python
    - ln -s -f /usr/local/python3/bin/pip3  /usr/bin/pip3  && ln -s -f /usr/local/bin/pip3 /usr/bin/pip
    # find qemu and gcc
    - cd $CI_PROJECT_DIR
    - export QEMU_PATH_LINUX=$(readlink -f linux_qemu/bin)
    - export PATH=$QEMU_PATH_LINUX:$PATH
    - export PATH=$CI_PROJECT_DIR/tools/gcc/gcc/bin:$PATH
    - qemu-system-riscv32 -M ?
    - riscv-nuclei-elf-gcc -v
    ################################################
    - cd $CI_PROJECT_DIR/tools/sdk/nuclei-sdk
    - pip3 install -r tools/scripts/requirements.txt
    - python3 tools/scripts/nsdk_cli/nsdk_bench.py --appcfg tools/scripts/nsdk_cli/configs/application.json --hwcfg tools/scripts/nsdk_cli/configs/nuclei_fpga_eval_ci_qemu.json --parallel=-j --logdir logs/nuclei_fpga_eval_qemu_ci --run --run_target "qemu"
  tags:
    - os::linux
    - env::docker
  image: ubuntu:16.04
  allow_failure: true
  artifacts:
    when: always
    paths:
    - $CI_PROJECT_DIR/tools/sdk/nuclei-sdk/logs/

test_nmsis:
  stage: test
  timeout: 2h 30m
  script:
    - apt-get -y update --fix-missing 
    - apt-get install -y --fix-missing cmake git build-essential pkg-config zlib1g-dev libglib2.0-0 libglib2.0-dev libpixman-1-dev autoconf automake libtool flex bison make
    #- apt-get install -y python3-pip
    - apt-get install -y software-properties-common
    - apt-get install wget openssl libssl-dev -y
    - wget http://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
    - tar -xvzf Python-3.6.4.tgz
    - cd Python-3.6.4
    - ./configure --with-ssl
    - make -j8 && make install
    - which python3
    - rm /usr/bin/python && ln -s /usr/local/bin/python3 /usr/bin/python
    - ln -s -f /usr/local/python3/bin/pip3  /usr/bin/pip3  && ln -s -f /usr/local/bin/pip3 /usr/bin/pip
    # find qemu and gcc
    - cd $CI_PROJECT_DIR
    - export QEMU_PATH_LINUX=$(readlink -f linux_qemu/bin)
    - export PATH=$QEMU_PATH_LINUX:$PATH
    - export PATH=$CI_PROJECT_DIR/tools/gcc/gcc/bin:$PATH
    - qemu-system-riscv32 -M ?
    - riscv-nuclei-elf-gcc -v
    ############################################################
    - cd $CI_PROJECT_DIR/tools/NMSIS/NMSIS/nuclei-sdk
    - pip3 install -r tools/scripts/requirements.txt
    - cd $CI_PROJECT_DIR/tools/NMSIS/
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei-sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - cd $CI_PROJECT_DIR/tools/NMSIS/NMSIS
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_dsp.json --logdir $NMSIS_LOGS/nmsis_dsp --parallel=-j --run_target qemu --run
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_nn.json  --logdir $NMSIS_LOGS/nmsis_nn  --parallel=-j --run_target qemu --run
  tags:
    - os::linux
    - env::docker
  image: ubuntu:16.04
  allow_failure: true
  artifacts:
    when: always
    paths:
    - $CI_PROJECT_DIR/tools/NMSIS/NMSIS/Logs

deploy-qemu:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - ls -al
    - apt-get update
    - apt-get -y install zip
    - cp $CI_PROJECT_DIR/tools/qemu.wiki/nuclei-qemu-版本发布说明.md windows_qemu/readme.md
    - cp $CI_PROJECT_DIR/tools/qemu.wiki/nuclei-qemu-版本发布说明.md linux_qemu/readme.md

    - mkdir -p windows_qemu_fold
    - mkdir -p linux_qemu_fold
    # windows qemu
    - cd $CI_PROJECT_DIR
    - cp windows_qemu windows_qemu_fold -r
    - cd $CI_PROJECT_DIR/windows_qemu_fold
    - mv windows_qemu qemu
    - cd qemu 
    - mkdir doc
    - cp $CI_PROJECT_DIR/tools/qemu.wiki/NUCLEI-QEMU-用户手册.pdf doc/nuclei_qemu_user_guide.pdf
    - cd ../
    - zip -r nuclei-qemu-2022.04-win32-x64.zip   qemu
    - cp nuclei-qemu-2022.04-win32-x64.zip $CI_PROJECT_DIR/
    # linux qemu
    - cd $CI_PROJECT_DIR
    - cp linux_qemu linux_qemu_fold -r
    - cd $CI_PROJECT_DIR/linux_qemu_fold
    - mv linux_qemu qemu
    - cd qemu 
    - mkdir doc
    - cp $CI_PROJECT_DIR/tools/qemu.wiki/NUCLEI-QEMU-用户手册.pdf doc/nuclei_qemu_user_guide.pdf
    - cd ../
    - tar -zcvf nuclei-qemu-2022.04-linux-x64.tar.gz   qemu
    - cp nuclei-qemu-2022.04-linux-x64.tar.gz $CI_PROJECT_DIR/
    # save log
    - mkdir $CI_PROJECT_DIR/test_logs
    - mkdir $CI_PROJECT_DIR/Documents
    - cp $CI_PROJECT_DIR/tools/sdk/nuclei-sdk/logs/ $CI_PROJECT_DIR/test_logs/ -r

    # docs
    #- git clone git@gito.corp.nucleisys.com:software/riscv-gnu-toolchain/qemu.wiki.git
    - cp $CI_PROJECT_DIR/tools/qemu.wiki/*pdf $CI_PROJECT_DIR/Documents -r
    - cp $CI_PROJECT_DIR/tools/qemu.wiki/nuclei-qemu-版本发布说明.md $CI_PROJECT_DIR/Documents -r
  tags:
    - env::docker
    - net::outside
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_$(date +%Y%m%d)"
    paths:
    - $CI_PROJECT_DIR/nuclei-qemu-2022.04-win32-x64.zip
    - $CI_PROJECT_DIR/nuclei-qemu-2022.04-linux-x64.tar.gz
    - $CI_PROJECT_DIR/test_logs/
    - $CI_PROJECT_DIR/Documents
